### ISSUE TITLE
Recipe for IEMOCAP (rnn_mm.sh) failing (vocab.txt missing)

### ISSUE THREAD

**Issue by pbrusco** [didi/delta#206]
I've been trying to run the multimodal-align-emotion.yml recipe for the speech emotion project (on IEMOCAP) and there is this "vocab.txt" file that is missing and I don't know where to get from. 

Steps:

1. `conda activate delta-py3.6-tf2.0.0`
2. `source env.sh`
3. `cd ./egs/iemocap/emo/v1`
4. `bash ./run_mm.sh`

Trace:
```
Traceback (most recent call last):
  File "/home/pbrusco/projects/delta/./delta/main.py", line 134, in <module>
    entry()
  File "/home/pbrusco/projects/delta/./delta/main.py", line 121, in entry
    app.run(main)
  File "/home/pbrusco/anaconda3/envs/delta-py3.6-tf2.0.0/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/pbrusco/anaconda3/envs/delta-py3.6-tf2.0.0/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/pbrusco/projects/delta/./delta/main.py", line 99, in main
    task = task_class(config, utils.INFER)
  File "/home/pbrusco/projects/delta/delta/data/task/speech_cls_task.py", line 881, in __init__
    super().__init__(config, mode)
  File "/home/pbrusco/projects/delta/delta/data/task/speech_cls_task.py", line 127, in __init__
    self.load_text_vocab_table()
  File "/home/pbrusco/projects/delta/delta/data/task/speech_cls_task.py", line 651, in load_text_vocab_table
    with open(self._vocab_path, 'r', encoding='utf-8') as vocab_f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/vocab.txt'
```

Also, I tried by running the main.py:
`python3 delta/main.py --cmd train_and_eval --config egs/mock_text_cls_data/text_cls/v1/config/han-cls.yml`

Didn't work either. 
```  
...
File "/home/pbrusco/projects/delta/delta/data/task/speech_cls_task.py", line 661, in generate_meta
    self.get_class_files_duration()
  File "/home/pbrusco/projects/delta/delta/data/task/speech_cls_task.py", line 340, in get_class_files_duration
    assert classes, 'can not acsess {}'.format(self._data_path[0])
AssertionError: can not acsess data/dump/all/train```
```
OS: Ubuntu 18.04.3 LTS

Any ideas? Thanks!

**Comment by xhyandwyy** [comment]
Hi, you need to download IEMOCAP dataset, and move it to iemocap_root path.
