### ISSUE TITLE
Recipe for IEMOCAP (run.sh) failing (TypeError)

### ISSUE THREAD

**Issue by pbrusco** [didi/delta#207]
I've been trying to run the recipe for the speech emotion project (on IEMOCAP) and there TypeError on `delta/models/speech_cls_model.py`.

Steps:

`conda activate delta-py3.6-tf2.0.0`
`source env.sh`
`cd ./egs/iemocap/emo/v1`
`bash ./run.sh`

Trace:

```
Traceback (most recent call last):
  File "/home/pbrusco/projects/delta/./delta/main.py", line 134, in <module>
    entry()
  File "/home/pbrusco/projects/delta/./delta/main.py", line 121, in entry
    app.run(main)
  File "/home/pbrusco/anaconda3/envs/delta-py3.6-tf2.0.0/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/pbrusco/anaconda3/envs/delta-py3.6-tf2.0.0/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/pbrusco/projects/delta/./delta/main.py", line 86, in main
    solver.train_and_eval()
  File "/home/pbrusco/projects/delta/delta/utils/solver/asr_solver.py", line 176, in train_and_eval
    self.model_fn(mode=utils.TRAIN)
  File "/home/pbrusco/projects/delta/delta/utils/solver/keras_base_solver.py", line 140, in model_fn
    self.build(multi_gpu=(mode == utils.TRAIN))
  File "/home/pbrusco/projects/delta/delta/utils/solver/keras_base_solver.py", line 154, in build
    self.model, gpus=self.ngpu, cpu_relocation=False, cpu_merge=False)
  File "/home/pbrusco/anaconda3/envs/delta-py3.6-tf2.0.0/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/pbrusco/anaconda3/envs/delta-py3.6-tf2.0.0/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/multi_gpu_utils.py", line 240, in multi_gpu_model
    outputs = model(inputs)
  File "/home/pbrusco/anaconda3/envs/delta-py3.6-tf2.0.0/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 847, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/pbrusco/anaconda3/envs/delta-py3.6-tf2.0.0/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in converted code:

    /home/pbrusco/projects/delta/delta/models/speech_cls_model.py:146 call  *
        x = inputs['inputs']

    TypeError: list indices must be integers or slices, not str
```

OS: Ubuntu 18.04.3 LTS

Any ideas? Thanks!

**Comment by xhyandwyy** [comment]
Hi，have you finished the fourth steps in run_mm.sh ?
