### ISSUE TITLE
FileNotFoundError: No x_ops*.so match under dir: /home/xubo/delta/core/ops

### ISSUE THREAD

**Issue by buglesxu** [didi/delta#213]
跑yahoo_answer dataset 时遇到的问题：
run_config:
    tf_random_seed: null
    allow_soft_placement: true
    log_device_placement: false
    intra_op_parallelism_threads: 10
    inter_op_parallelism_threads: 10
    allow_growth: true
[ 2020-07-02 17:57:52,623 INFO         main.py:69    22512 ]  Loading all modules ...
Traceback (most recent call last):
  File "/home/xubo/delta/core/ops/py_x_ops.py", line 27, in <module>
    so_lib_file = tf.io.gfile.glob(file_dir + '/x_ops*.so')[0].split('/')[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "delta/delta/main.py", line 134, in <module>
    entry()
  File "delta/delta/main.py", line 121, in entry
    app.run(main)
  File "/home/xubo/anaconda3/envs/delta-pip-py3.6/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/xubo/anaconda3/envs/delta-pip-py3.6/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "delta/delta/main.py", line 70, in main
    import_all_modules_for_register(config, only_nlp=FLAGS.only_nlp)
  File "/home/xubo/delta/delta/utils/register.py", line 228, in import_all_modules_for_register
    importlib.import_module(full_name)
  File "/home/xubo/anaconda3/envs/delta-pip-py3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/xubo/delta/delta/data/task/text_cls_task.py", line 22, in <module>
    from delta.data.task.base_text_task import TextTask
  File "/home/xubo/delta/delta/data/task/base_text_task.py", line 24, in <module>
    from delta.data.preprocess.text_ops import clean_english_str_tf
  File "/home/xubo/delta/delta/data/preprocess/text_ops.py", line 22, in <module>
    from core.ops import py_x_ops
  File "/home/xubo/delta/core/ops/py_x_ops.py", line 29, in <module>
    raise FileNotFoundError(f"No x_ops*.so match under dir: {file_dir}")
FileNotFoundError: No x_ops*.so match under dir: /home/xubo/delta/core/ops

**Comment by buglesxu** [comment]
is anyone can help me? 555

**Comment by zh794390558** [comment]
You need install delta first, please see doc for details.

**Comment by buglesxu** [comment]
> You need install delta first, please see doc for details.

I already installed delta, I did follow the doc. Thanks.

**Comment by zh794390558** [comment]
Does TF is 2.0.0 and any *.so under /home/xubo/delta/core/ops ?

**Comment by zh794390558** [comment]
You can follow [this](https://github.com/didi/delta/blob/master/tools/Makefile#L86) to compile ops.

**Comment by zh794390558** [comment]
If any error occurs , please check this https://github.com/didi/delta/blob/master/core/ops/build.sh#L28

**Comment by buglesxu** [comment]
> If any error occurs , please check this https://github.com/didi/delta/blob/master/core/ops/build.sh#L28

Thank you very much, I will try again a few days later

**Comment by zh794390558** [comment]
Any questions can reopen this issue.
