### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.6/dist-packages/delta/layers/ops/x_ops.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN4absl14ascii_internal13kPropertyBitsE

### ISSUE THREAD

**Issue by XuJianzhi** [didi/delta#257]
>>> import delta.compat as tf
2021-01-18 02:39:57.852065: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
>>> from delta.models.base_model import Model
>>> from delta.models.base_model import Model
>>> from delta.layers.utils import get_seg_mask_from_token_idx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/delta/layers/__init__.py", line 27, in <module>
    from delta.layers.common_layers import *
  File "/usr/local/lib/python3.6/dist-packages/delta/layers/common_layers.py", line 21, in <module>
    from delta.data.feat import speech_ops
  File "/usr/local/lib/python3.6/dist-packages/delta/data/feat/__init__.py", line 17, in <module>
    from delta.data.feat import speech_ops
  File "/usr/local/lib/python3.6/dist-packages/delta/data/feat/speech_ops.py", line 26, in <module>
    from delta.layers.ops import py_x_ops
  File "/usr/local/lib/python3.6/dist-packages/delta/layers/ops/py_x_ops.py", line 38, in <module>
    gen_x_ops = tf.load_op_library(path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.6/dist-packages/delta/layers/ops/x_ops.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN4absl14ascii_internal13kPropertyBitsE

![image](https://user-images.githubusercontent.com/30584453/104866717-31b8aa00-597a-11eb-95a6-81a845fb9437.png)

Ubuntu 18.04.5 LTS, dokcer, python-3.6.1, tensorflow-gpu-2.3.1, cuda-10.1, no cudnn

**Comment by sihwa-park** [comment]
I changed
from delta.layers.ops import py_x_ops
to
from delta.core.ops import py_x_ops
and copied core directory from github source.
Also I ran build bash file in core/ops directory.
