### ISSUE TITLE
Fail to load model for iemocap evaluation.

### ISSUE THREAD

**Issue by Saduras** [didi/delta#42]
**Describe the bug**
When trying to run an evaluation run with the iemocap example after training a model it fails with:
```
Traceback (most recent call last):
  File "../../delta/delta/main.py", line 111, in <module>
    app.run(main)
  File "/home/david175/miniconda3/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/david175/miniconda3/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "../../delta/delta/main.py", line 81, in main
    solver.eval()
  File "/home/david175/project/delta/delta/utils/solver/emotion_solver.py", line 132, in eval
    self.model_fn(mode=utils.EVAL)
  File "/home/david175/project/delta/delta/utils/solver/asr_solver.py", line 193, in model_fn
    self.model.load_weights(str(model_path))
  File "/home/david175/miniconda3/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 162, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/home/david175/miniconda3/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1424, in load_weights
    saving.load_weights_from_hdf5_group(f, self.layers)
  File "/home/david175/miniconda3/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 737, in load_weights_from_hdf5_group
    ' layers.')
ValueError: You are trying to load a weight file containing 3 layers into a model with 0 layers.
```

**To Reproduce**
Requires full installation of delta & iemocap dataset. Steps to reproduce the behavior:
1. Set root path to iemocap dataset in `egs/iemocap/emo/v1/run.sh`
2. For faster repro set epochs to 1 in `egs/iemocap/emo/v1/conf/emo-keras-blstm.yml`
3. Change to directory `egs/iemocap/emo/v1`
3. Run `./run.sh`
4. After training run  'python3 -u ../../../../delta/main.py **--cmd eval** --config conf/emo-keras-blstm.yml'
5. See error

**Expected behavior**
The evaluation runs without errors.

**Additional Information**
Tried it with keras `2.2.4` and `2.1.0`. Both produce the same error.

**Comment by zh794390558** [comment]
see this https://github.com/tensorflow/tensorflow/issues/30892.
I will check if eval can work, `train_and_eval` is recommended.

**Comment by Saduras** [comment]
I don't think the issue is related. It seems rather to have something to do with dynamic shapes. I found an (awful) hacky workaround by adding
```
self.model.fit({'inputs': np.zeros((1,700,257,1)), 'labels':np.array([0])}, epochs=0)
```
in `asr_solver.build` after `self.model.compile()`. This seems to cause all layers of the model to be build properly, while compile leaves something unbuilt.

**Comment by zh794390558** [comment]
relevant issue https://github.com/keras-team/keras/issues/11072

**Comment by zh794390558** [comment]
This error is cause by `.h5` model , please using `tensorflow model` instead.
