### ISSUE TITLE
安装./install/install-delta.sh nlp cpu报错

### ISSUE THREAD

**Issue by Hejp5665** [didi/delta#9]
SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/main/noarch/repodata.json.bz2 (Caused by SSLError(SSLError("bad handshake: SysCallError(104, \'ECONNRESET\')",),))',),)
这个怎么解决

**Comment by applenob** [comment]
这么看应该是安装时期的网络错误，建议重新安装下。

建议国内用户把安装脚本里面关于软件源的注释打开`tools/install/install-delta.sh`：

```shell
# If you are a user from mainland China, you can use following codes to speed up the installation.
# conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
# conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
# conda config --set show_channel_urls yes
# pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
```

如果还有问题麻烦提供下更完整的log。

**Comment by Hejp5665** [comment]
嗯，谢谢你的回复，问题已经解决，现在又有了新的问题
我在运行 python3 delta/main.py --cmd train --config egs/conll2003/seq_label/v1/config/seq-label.yml
出现这样问题错误，请问这个是什么原因导致的
[ 2019-08-05 17:06:07,170 INFO     py_x_ops.py:24    372969 ]  x_ops.so path:/home/data01/software/delta/delta/layers/ops/x_ops.so
Traceback (most recent call last):
  File "delta/main.py", line 111, in <module>
    app.run(main)
  File "/home/data01/anaconda3/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/data01/anaconda3/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "delta/main.py", line 64, in main
    import_all_modules_for_register()
  File "/home/data01/software/delta/delta/utils/register.py", line 141, in import_all_modules_for_register
    importlib.import_module(full_name)
  File "/home/data01/anaconda3/envs/delta-py3.6-tf1.14/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/data01/software/delta/delta/data/task/asr_seq_task.py", line 22, in <module>
    from delta.data.utils import espnet_utils
  File "/home/data01/software/delta/delta/data/utils/__init__.py", line 17, in <module>
    from delta.data.utils.common_utils import *
  File "/home/data01/software/delta/delta/data/utils/common_utils.py", line 26, in <module>
    from delta.data.preprocess.text_ops import tokenize_label
  File "/home/data01/software/delta/delta/data/preprocess/text_ops.py", line 23, in <module>
    from delta.layers.ops import py_x_ops
  File "/home/data01/software/delta/delta/layers/ops/py_x_ops.py", line 27, in <module>
    tf.compat.v1.resource_loader.get_path_to_datafile('x_ops.so'))
  File "/home/data01/anaconda3/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/data01/software/delta/delta/layers/ops/x_ops.so: undefined symbol: _ZN10tensorflow8str_util9LowercaseEN4absl11string_viewE

**Comment by applenob** [comment]
麻烦提供下你的g++版本

**Comment by Hejp5665** [comment]
(delta-py3.6-tf1.14) [data01@localhost data]$ g++ -v 
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

**Comment by applenob** [comment]
这个是自定义op编译的问题。现在tensorflow在用g++4.8编译custom op的时候偶尔会有这个bug。

可以使用`conda install -c conda-forge cxx-compiler`升级下当前conda环境的g++版本。

然后重新编译下custom op：

```shell
pushd delta/layers/ops/
./build.sh delta
popd
```

**Comment by Hejp5665** [comment]
感谢问题已解决
